package entity;

import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.validation.constraints.*;
import java.time.LocalDate;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Entity(name = "employee")
@Table(name = "employee")
public class EmployeeEntity {

    @Id
    private String empId;  // Auto-generated by the database.

    @NotBlank(message = "Title cannot be blank")
    private String empTitle;

    @NotBlank(message = "Name cannot be blank")
    @Size(min = 2, message = "Name must have at least 2 characters")
    private String empName;

    @NotBlank(message = "NIC cannot be blank")
    @Pattern(regexp = "^[0-9]{9}[vVxX]$", message = "NIC must follow the format of 9 digits followed by V/v/X/x")
    private String empNic;

    @NotBlank(message = "Email cannot be blank")
    @Email(message = "Email must be valid")
    private String empEmail;

    @NotNull(message = "Birthday cannot be null")
    @Past(message = "Birthday must be in the past")
    private LocalDate empBirthday;

    @NotNull(message = "Contact number cannot be null")
    @Pattern(regexp = "^[0-9]{10}$", message = "Contact number must be 10 digits")
    private String empContact;

    @NotBlank(message = "Address cannot be blank")
    private String empAddress;
}
